# go.yml
_format_version: "1.1"
services:
- url: https://httpbin.org
  routes:
  - paths:
    - "/"
  plugins:
  - name: file-log
    config:
      path: /var/log/kong/proxy.log
      custom_fields_by_lua:
        route: return nil
        service: return nil
